---
- name: Create Python virtual environment
  ansible.builtin.shell: "cd {{ venv_directory }} && python3.12 -m venv venv"
  register: shell_output_create_venv
  retries: 3
  delay: 10
  until: shell_output_create_venv.rc == 0
  tags:
    - sre_agent

- name: Set up UV
  ansible.builtin.shell: "source {{ venv_directory }}/bin/activate && pip install --no-input uv"
  register: shell_output_setup_uv
  retries: 3
  delay: 10
  until: shell_output_setup_uv.rc == 0
  tags:
    - sre_agent
