finops_human_input_query_task:
  description: >
    A mechanism to take input from the human.
  expected_output: >
    Query from the human in natural language.
  agent: finops_data_query_agent

finops_data_query_task:
  description: >
    Given a request in natural language return the relevant data from MySQL
  expected_output: >
    Return output data from the query.
  agent: finops_data_query_agent

finops_anomaly_detection_task:
  description: >
    Given a request in natural language to detect if there are any anomalies present in the requested data.
    First step is to gather the required data from MySQL database using NL2SQLClickHouseCustomTool.
    Then use the NL2AnomalyDetectionCustomTool tool to identify any anomalies present in the data.
  expected_output: >
    A report with summary of the returned data
  agent: finops_anomaly_detection_agent
