"""Prompts for ITBench LLM-as-a-Judge evaluation."""

from .entity_correctness import (
    ENTITY_CORRECTNESS_STEPS,
    ROOT_CAUSE_ENTITY_OUTPUT_FORMAT,
    ROOT_CAUSE_ENTITY_PROMPT,
)
from .entity_correctness_k import (
    ROOT_CAUSE_ENTITY_K_OUTPUT_FORMAT,
    ROOT_CAUSE_ENTITY_K_PROMPT,
)
from .fault_localization import (
    FAULT_LOCALIZATION_OUTPUT_FORMAT,
    FAULT_LOCALIZATION_PROMPT,
)
from .reasoning_correctness import (
    REASONING_CORRECTNESS_STEPS,
    ROOT_CAUSE_REASONING_OUTPUT_FORMAT,
    ROOT_CAUSE_REASONING_PROMPT,
)
from .reasoning_partial import (
    ROOT_CAUSE_REASONING_PARTIAL_OUTPUT_FORMAT,
    ROOT_CAUSE_REASONING_PARTIAL_PROMPT,
)
from .propagation_chain import (
    PROPAGATION_CHAIN_OUTPUT_FORMAT,
    PROPAGATION_CHAIN_PROMPT,
)
from .few_shot import (
    PARTIALLY_CORRECT_REASONING_FEW_SHOT,
    INCIDENT_SPECIFIC_FULLY_CORRECT_REASONING,
    INCIDENT_SPECIFIC_PARTIALLY_CORRECT_REASONING,
    FULLY_CORRECT_REASONING_FEW_SHOT,
)
from .proximity import (
    ROOT_CAUSE_PROXIMITY_OUTPUT_FORMAT,
    ROOT_CAUSE_PROXIMITY_PROMPT,
)
from .proximity_fp import (
    ROOT_CAUSE_PROXIMITY_FP_OUTPUT_FORMAT,
    ROOT_CAUSE_PROXIMITY_FP_PROMPT,
)
from .semantic_grouping import (
    SEMANTIC_GROUPING_PROMPT,
    NO_SEMANTIC_GROUPING_PROMPT,
)
from .main import (
    EVALUATE_PROMPT_TEMPLATE,
    LAAJ_SYSTEM_PROMPT,
)

__all__ = [
    # Entity correctness
    "ENTITY_CORRECTNESS_STEPS",
    "ROOT_CAUSE_ENTITY_OUTPUT_FORMAT",
    "ROOT_CAUSE_ENTITY_PROMPT",
    # Entity correctness @k
    "ROOT_CAUSE_ENTITY_K_OUTPUT_FORMAT",
    "ROOT_CAUSE_ENTITY_K_PROMPT",
    # Fault localization
    "FAULT_LOCALIZATION_OUTPUT_FORMAT",
    "FAULT_LOCALIZATION_PROMPT",
    # Reasoning correctness
    "REASONING_CORRECTNESS_STEPS",
    "ROOT_CAUSE_REASONING_OUTPUT_FORMAT",
    "ROOT_CAUSE_REASONING_PROMPT",
    # Reasoning partial
    "ROOT_CAUSE_REASONING_PARTIAL_OUTPUT_FORMAT",
    "ROOT_CAUSE_REASONING_PARTIAL_PROMPT",
    # Propagation chain
    "PROPAGATION_CHAIN_OUTPUT_FORMAT",
    "PROPAGATION_CHAIN_PROMPT",
    # Few shot examples
    "PARTIALLY_CORRECT_REASONING_FEW_SHOT",
    "INCIDENT_SPECIFIC_FULLY_CORRECT_REASONING",
    "INCIDENT_SPECIFIC_PARTIALLY_CORRECT_REASONING",
    "FULLY_CORRECT_REASONING_FEW_SHOT",
    # Proximity
    "ROOT_CAUSE_PROXIMITY_OUTPUT_FORMAT",
    "ROOT_CAUSE_PROXIMITY_PROMPT",
    # Proximity with FP
    "ROOT_CAUSE_PROXIMITY_FP_OUTPUT_FORMAT",
    "ROOT_CAUSE_PROXIMITY_FP_PROMPT",
    # Semantic grouping
    "SEMANTIC_GROUPING_PROMPT",
    "NO_SEMANTIC_GROUPING_PROMPT",
    # Main prompts
    "EVALUATE_PROMPT_TEMPLATE",
    "LAAJ_SYSTEM_PROMPT",
]
